VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IPersonalDal"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Function getAkademikPersonelsByBolumIdToColl(bolum As EFBolum, katilanlar As Boolean) As Collection

End Function

Function getAkademikPersonelsByBolumIdToArr(bolum As EFBolum, katilanlar As Boolean) As Variant

End Function

Function getDekanIdOnly() As Integer

End Function
