VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "mKararManager"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Function getKararsByTopId(toplanti As EFToplanti) As Variant

''Bir toplantýnýn kararlarý

End Function

Function getKararByKararId(karar As EFKarar) As EFKarar

End Function

Sub updateKararBaslik(karar As EFKarar, newBaslik As String)


End Sub

Sub updateKararIcerik(karar As EFKarar, newContent As String)


End Sub

Sub updateKararToplantiId(karar As EFKarar, toplanti As EFToplanti)

End Sub
